import { motion } from 'framer-motion';
import { 
  Eye, Brain, Wrench, CheckCircle, RefreshCw, 
  ArrowRight, Database, Shield, Cpu
} from 'lucide-react';

export default function Architecture() {
  const phases = [
    {
      icon: <Eye className="w-6 h-6" />,
      title: 'Observe',
      color: 'blue',
      description: 'Parse the input — extract the message, financial context, and any loan offers. Determine what data is available.',
      details: 'Message parsing, entity extraction, context assembly',
    },
    {
      icon: <Brain className="w-6 h-6" />,
      title: 'Decide',
      color: 'purple',
      description: 'Dynamically select which tools to call based on what the input actually contains. Not a fixed script — the right set of checks is a function of the specific situation.',
      details: 'Tool selection, dependency analysis, input routing',
    },
    {
      icon: <Wrench className="w-6 h-6" />,
      title: 'Act',
      color: 'emerald',
      description: 'Execute deterministic tools (scam scanner, cash flow projector, loan cost calculator). All numbers are computed, never generated by the LLM.',
      details: 'scan_message_for_scams, forecast_cash_flow, compute_true_loan_cost',
    },
    {
      icon: <CheckCircle className="w-6 h-6" />,
      title: 'Evaluate',
      color: 'amber',
      description: 'Cross-check all tool outputs against each other. Does the recommendation actually resolve the situation? Are there contradictions or gaps?',
      details: 'Result validation, contradiction detection, gap analysis',
    },
    {
      icon: <RefreshCw className="w-6 h-6" />,
      title: 'Adapt',
      color: 'cyan',
      description: 'If the first answer is incomplete (e.g., avoiding the loan still leaves a shortfall), go back for a more complete solution — or honestly state what couldn\'t be resolved.',
      details: 'Alternative search, escalation decision, gap acknowledgment',
    },
  ];

  const colorMap: Record<string, { bg: string; border: string; text: string; glow: string }> = {
    blue: { bg: 'bg-blue-500/10', border: 'border-blue-500/20', text: 'text-blue-400', glow: 'shadow-blue-500/20' },
    purple: { bg: 'bg-purple-500/10', border: 'border-purple-500/20', text: 'text-purple-400', glow: 'shadow-purple-500/20' },
    emerald: { bg: 'bg-emerald-500/10', border: 'border-emerald-500/20', text: 'text-emerald-400', glow: 'shadow-emerald-500/20' },
    amber: { bg: 'bg-amber-500/10', border: 'border-amber-500/20', text: 'text-amber-400', glow: 'shadow-amber-500/20' },
    cyan: { bg: 'bg-cyan-500/10', border: 'border-cyan-500/20', text: 'text-cyan-400', glow: 'shadow-cyan-500/20' },
  };

  return (
    <section className="min-h-screen pt-20 pb-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-16">
          <h2 className="text-3xl sm:text-4xl font-bold mb-4 bg-gradient-to-r from-white to-slate-300 bg-clip-text text-transparent">
            System Architecture
          </h2>
          <p className="text-slate-400 max-w-2xl mx-auto">
            The observe → decide → act → evaluate → adapt loop. Not a single-turn Q&A — 
            a genuine agentic cycle that checks its own work and adapts when the first answer isn't enough.
          </p>
        </div>

        {/* Agent Loop Diagram */}
        <div className="relative mb-20">
          <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
            {phases.map((phase, i) => {
              const colors = colorMap[phase.color];
              return (
                <motion.div
                  key={phase.title}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.1 }}
                  viewport={{ once: true }}
                  className="relative"
                >
                  <div className={`${colors.bg} border ${colors.border} rounded-2xl p-5 h-full transition-all hover:shadow-lg ${colors.glow}`}>
                    <div className={`${colors.text} mb-3`}>{phase.icon}</div>
                    <h3 className={`text-lg font-bold ${colors.text} mb-2`}>{phase.title}</h3>
                    <p className="text-sm text-slate-400 leading-relaxed mb-3">{phase.description}</p>
                    <div className="text-xs text-slate-600 font-mono bg-slate-800/30 rounded-lg px-2 py-1">
                      {phase.details}
                    </div>
                  </div>
                  {i < 4 && (
                    <div className="hidden md:flex absolute top-1/2 -right-3 transform -translate-y-1/2 z-10">
                      <ArrowRight className="w-5 h-5 text-slate-600" />
                    </div>
                  )}
                </motion.div>
              );
            })}
          </div>
          
          {/* Loop-back arrow */}
          <div className="hidden md:block absolute bottom-0 left-0 right-0 h-8">
            <div className="absolute bottom-0 left-[10%] right-[10%] h-px bg-gradient-to-r from-cyan-500/30 via-slate-600/30 to-blue-500/30" />
            <div className="absolute bottom-0 left-[10%] w-px h-4 bg-cyan-500/30" />
            <div className="absolute bottom-0 right-[10%] w-px h-4 bg-blue-500/30" />
            <div className="absolute -bottom-5 left-1/2 -translate-x-1/2 text-xs text-slate-600 flex items-center gap-1">
              <RefreshCw className="w-3 h-3" />
              Loop back if evaluation finds gaps
            </div>
          </div>
        </div>

        {/* Key Design Principles */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">
          <PrincipleCard
            icon={<Database className="w-6 h-6 text-emerald-400" />}
            title="Deterministic Math"
            description="Every rupee figure is computed by Python functions, never generated by the LLM. The LLM decides which tool to call and how to explain the result — never invents a number."
          />
          <PrincipleCard
            icon={<Shield className="w-6 h-6 text-cyan-400" />}
            title="Auditable Trace"
            description="Every step is logged with its inputs, tool calls, and outputs. The full reasoning chain is inspectable — not a black box that produces an answer from nowhere."
          />
          <PrincipleCard
            icon={<Cpu className="w-6 h-6 text-purple-400" />}
            title="Dynamic Tool Selection"
            description="Not every input needs every check. The right set of tools is decided per-situation based on what the input actually contains — not a fixed script."
          />
        </div>

        {/* Why Agentic */}
        <div className="bg-slate-900/50 border border-slate-800 rounded-2xl p-8">
          <h3 className="text-xl font-bold text-white mb-6">Why This Requires an Agent (Not a Single LLM Call)</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <ComparisonItem
                label="Single LLM Call"
                items={[
                  'Fixed prompt, fixed output format',
                  'Cannot chain tool outputs dependently',
                  'No self-checking mechanism',
                  'May generate plausible-sounding but wrong numbers',
                  'Cannot go back and fix an incomplete answer',
                ]}
                color="red"
              />
            </div>
            <div className="space-y-4">
              <ComparisonItem
                label="Agentic Loop (UPI Rakshak)"
                items={[
                  'Dynamic tool selection per input',
                  'Sequential, dependency-chained computation',
                  'Self-checks recommendation against actual data',
                  'All numbers from deterministic functions',
                  'Adapts when first answer is incomplete',
                ]}
                color="emerald"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function PrincipleCard({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="bg-slate-900/50 border border-slate-800 rounded-2xl p-6"
    >
      <div className="mb-3">{icon}</div>
      <h3 className="text-lg font-semibold text-white mb-2">{title}</h3>
      <p className="text-sm text-slate-400 leading-relaxed">{description}</p>
    </motion.div>
  );
}

function ComparisonItem({ label, items, color }: { label: string; items: string[]; color: string }) {
  const colors = color === 'red' 
    ? { border: 'border-red-500/20', bg: 'bg-red-500/5', text: 'text-red-400', bullet: 'text-red-500' }
    : { border: 'border-emerald-500/20', bg: 'bg-emerald-500/5', text: 'text-emerald-400', bullet: 'text-emerald-500' };

  return (
    <div className={`border ${colors.border} ${colors.bg} rounded-xl p-4`}>
      <h4 className={`font-bold ${colors.text} mb-3`}>{label}</h4>
      <ul className="space-y-2">
        {items.map((item, i) => (
          <li key={i} className="flex items-start gap-2 text-sm text-slate-400">
            <span className={`${colors.bullet} mt-1`}>•</span>
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}
